/*
 * Вторая часть графа: темы, которых не было в хакатонной версии, — чтобы по каждой из 18 тем
 * спецификации ЕНТ по математике (НЦТ, с 2026 года) в графе была хотя бы одна тема.
 * Новые темы добавляются В КОНЕЦ списка: коды «ученик → учитель» старой версии (17 тем) остаются читаемыми.
 * Формат тот же, что в data.js. Уровень — базовый, задачи без чертежей.
 */
(function () {
  const T = window.Tamyr;

  T.TOPICS.push(
    { id: 'trig', short: 'Тригонометрия', title: 'Тригонометрия: значения и тождества', level: 3, prereq: ['root', 'frac'],
      rule: 'sin²α + cos²α = 1;  tg α = sin α / cos α. Значения для 30°, 45°, 60° нужно знать: sin 30° = 1/2, sin 45° = √2/2, sin 60° = √3/2; у косинуса — в обратном порядке.',
      example: 'sin α = 3/5, α в I четверти → cos α = √(1 − 9/25) = 4/5' },
    { id: 'planfig', short: 'Планиметрия', title: 'Планиметрия: углы и фигуры', level: 4, prereq: ['lin'],
      rule: 'Сумма углов треугольника 180°, четырёхугольника — 360°. Смежные углы в сумме дают 180°, вертикальные равны. В равнобедренном треугольнике углы при основании равны. Вписанный угол равен половине центрального, опирающегося на ту же дугу.',
      example: 'Углы треугольника 50° и 60° → третий 180° − 110° = 70°' },
    { id: 'exp', short: 'Показат. уравн.', title: 'Показательные уравнения', level: 5, prereq: ['pow', 'lin'],
      rule: 'Приведите обе части к одному основанию: если a^f = a^g (a > 0, a ≠ 1), то f = g. Помните: a⁰ = 1, a⁻ⁿ = 1/aⁿ.',
      example: '2^x = 8 → 2^x = 2³ → x = 3' },
    { id: 'prog', short: 'Прогрессии', title: 'Арифметическая и геометрическая прогрессии', level: 5, prereq: ['lin', 'pow'],
      rule: 'Арифметическая: aₙ = a₁ + (n − 1)d,  Sₙ = (a₁ + aₙ)·n / 2. Геометрическая: bₙ = b₁·qⁿ⁻¹,  Sₙ = b₁(qⁿ − 1)/(q − 1).',
      example: 'a₁ = 2, d = 3 → a₅ = 2 + 4·3 = 14' },
    { id: 'trigeq', short: 'Триг. уравнения', title: 'Тригонометрические уравнения', level: 5, prereq: ['trig', 'lin'],
      rule: 'sin x = a: x = (−1)ⁿ·arcsin a + πn;  cos x = a: x = ±arccos a + 2πn;  tg x = a: x = arctg a + πn, n ∈ Z. При |a| > 1 уравнения sin x = a и cos x = a решений не имеют.',
      example: 'cos x = 1/2 → x = ±π/3 + 2πn, n ∈ Z' },
    { id: 'planmet', short: 'Пифагор, площ.', title: 'Теорема Пифагора, площади, подобие', level: 5, prereq: ['planfig', 'root', 'prop'],
      rule: 'Теорема Пифагора: c² = a² + b². Площади: прямоугольник a·b, треугольник a·h/2, круг πr², трапеция (a + b)·h/2. У подобных фигур стороны относятся как k, а площади — как k².',
      example: 'Катеты 3 и 4 → гипотенуза √(9 + 16) = 5' },
    { id: 'ratq', short: 'Рац. уравнения', title: 'Дробно-рациональные уравнения', level: 6, prereq: ['quad', 'fact', 'frac'],
      rule: 'Найдите ОДЗ: знаменатель не равен нулю. Умножьте обе части на общий знаменатель, решите полученное уравнение и отбросьте корни, не входящие в ОДЗ.',
      example: '(x² − 4)/(x − 2) = 0 → x² = 4, x ≠ 2 → x = −2' },
    { id: 'qineq', short: 'Кв. неравенства', title: 'Квадратные и рациональные неравенства', level: 6, prereq: ['quad', 'ineq'],
      rule: 'Найдите нули, отметьте их на числовой прямой и определите знак на каждом интервале (метод интервалов). Точки, где знаменатель равен нулю, в ответ не входят никогда.',
      example: 'x² − 5x + 6 < 0 → нули 2 и 3 → 2 < x < 3' },
    { id: 'nlsys', short: 'Нелин. системы', title: 'Системы нелинейных уравнений', level: 6, prereq: ['sys', 'quad'],
      rule: 'Выразите одну переменную из более простого уравнения и подставьте в другое. Получится квадратное уравнение; для каждого его корня найдите вторую переменную.',
      example: 'x + y = 5, xy = 6 → x(5 − x) = 6 → (2; 3) и (3; 2)' },
    { id: 'irr', short: 'Иррац. уравн.', title: 'Иррациональные уравнения', level: 6, prereq: ['root', 'quad'],
      rule: 'Уедините корень и возведите обе части в квадрат. Возведение в квадрат может дать посторонние корни — каждый найденный корень проверьте подстановкой.',
      example: '√(x + 2) = x → x + 2 = x² → x = 2 (x = −1 — посторонний корень)' },
    { id: 'log', short: 'Логарифмы', title: 'Логарифмы и логарифмические уравнения', level: 6, prereq: ['exp'],
      rule: 'logₐ b = c означает a^c = b (a > 0, a ≠ 1, b > 0). Логарифм произведения равен сумме логарифмов, логарифм степени: logₐ bⁿ = n·logₐ b. В уравнении проверяйте, что выражение под логарифмом положительно.',
      example: 'log₂ 8 = 3, потому что 2³ = 8;  log₃ x = 2 → x = 9' },
    { id: 'sysineq', short: 'Системы нер-в', title: 'Системы неравенств', level: 7, prereq: ['qineq'],
      rule: 'Решите каждое неравенство отдельно и возьмите пересечение решений — те x, которые подходят всем неравенствам сразу.',
      example: 'x > 1 и x ≤ 4 → 1 < x ≤ 4' },
    { id: 'elsys', short: 'Показ. и лог.', title: 'Показательные и логарифмические неравенства и системы', level: 7, prereq: ['log', 'ineq', 'sys'],
      rule: 'При основании a > 1 знак неравенства сохраняется при переходе к показателям (или к выражениям под логарифмом), при 0 < a < 1 — меняется на противоположный. Для логарифма добавьте условие: выражение под логарифмом больше нуля.',
      example: '2^x > 8 → x > 3;  (1/2)^x > 4 → x < −2' },
    { id: 'deriv', short: 'Производная', title: 'Производная', level: 7, prereq: ['pow', 'linf', 'quad'],
      rule: '(xⁿ)′ = n·xⁿ⁻¹;  производная числа равна 0;  (f + g)′ = f′ + g′;  (k·f)′ = k·f′. Значение f′(x₀) — угловой коэффициент касательной; в точках экстремума f′(x) = 0.',
      example: 'f(x) = x³ − 2x → f′(x) = 3x² − 2,  f′(1) = 1' },
    { id: 'solid', short: 'Стереометрия', title: 'Фигуры в пространстве', level: 7, prereq: ['planmet'],
      rule: 'У куба 6 граней, 12 рёбер, 8 вершин. Диагональ прямоугольного параллелепипеда: d² = a² + b² + c². У n-угольной призмы 3n рёбер и n + 2 грани, у n-угольной пирамиды 2n рёбер и n + 1 грань.',
      example: 'Диагональ куба с ребром 2: d = √(4 + 4 + 4) = 2√3' },
    { id: 'vec', short: 'Векторы', title: 'Векторы на плоскости', level: 7, prereq: ['planmet', 'linf'],
      rule: 'Координаты вектора AB = (x_B − x_A; y_B − y_A). Длина |a| = √(x² + y²). Скалярное произведение a·b = x₁x₂ + y₁y₂; векторы перпендикулярны, когда оно равно нулю.',
      example: 'a = (3; 4) → |a| = √(9 + 16) = 5' },
    { id: 'integ', short: 'Интеграл', title: 'Первообразная и интеграл', level: 8, prereq: ['deriv'],
      rule: 'Первообразная для xⁿ — это xⁿ⁺¹/(n + 1) + C. Определённый интеграл: ∫ₐᵇ f(x)dx = F(b) − F(a).',
      example: '∫₀² 3x² dx = x³ |₀² = 8 − 0 = 8' },
    { id: 'solmet', short: 'Объёмы', title: 'Объёмы и площади поверхностей', level: 8, prereq: ['solid'],
      rule: 'Объём: призма и цилиндр — S_осн·h, пирамида и конус — S_осн·h/3, шар — 4πR³/3. Поверхность куба 6a², боковая поверхность цилиндра 2πRh, поверхность шара 4πR².',
      example: 'Цилиндр R = 2, h = 5: V = π·4·5 = 20π' },
    { id: 'vec3', short: 'Векторы 3D', title: 'Векторы в пространстве', level: 8, prereq: ['vec'],
      rule: 'Всё как на плоскости, но координат три: |a| = √(x² + y² + z²),  a·b = x₁x₂ + y₁y₂ + z₁z₂. Середина отрезка — полусумма координат концов.',
      example: 'a = (1; 2; 2) → |a| = √(1 + 4 + 4) = 3' }
  );

  Object.assign(T.MISCONCEPTIONS, {
    trig_swap:         { home: 'trig',    title: 'Путает значения синуса и косинуса для 30° и 60°', fix: 'sin 30° = cos 60° = 1/2;  sin 60° = cos 30° = √3/2.' },
    trig_identity:     { home: 'trig',    title: 'Считает, что sin α + cos α = 1 (без квадратов)', fix: 'Тождество: sin²α + cos²α = 1.' },
    trig_sign_quarter: { home: 'trig',    title: 'Не учитывает знак функции в четверти', fix: 'Во II четверти синус положителен, косинус отрицателен.' },
    angle_sum:         { home: 'planfig', title: 'Использует неверную сумму углов (360° для треугольника или 180° для четырёхугольника)', fix: 'Треугольник — 180°, четырёхугольник — 360°.' },
    adjacent_vertical: { home: 'planfig', title: 'Путает смежные и вертикальные углы', fix: 'Вертикальные углы равны, смежные в сумме дают 180°.' },
    inscribed_central: { home: 'planfig', title: 'Считает вписанный угол равным центральному', fix: 'Вписанный угол равен половине центрального.' },
    exp_neg_power:     { home: 'exp',     title: 'Считает, что отрицательный показатель даёт отрицательное число', fix: 'a⁻ⁿ = 1/aⁿ — число положительное.' },
    exp_base:          { home: 'exp',     title: 'Приравнивает показатели, не приведя степени к одному основанию', fix: 'Сначала одно основание: 4 = 2², 8 = 2³.' },
    prog_n:            { home: 'prog',    title: 'Умножает разность на n вместо n − 1', fix: 'aₙ = a₁ + (n − 1)d: до n-го члена n − 1 шаг.' },
    prog_mix:          { home: 'prog',    title: 'Путает арифметическую и геометрическую прогрессии', fix: 'В арифметической прибавляют d, в геометрической умножают на q.' },
    trig_one_series:   { home: 'trigeq',  title: 'Записывает одно значение вместо всей серии решений', fix: 'У тригонометрического уравнения бесконечно много решений: добавьте период.' },
    trig_period:       { home: 'trigeq',  title: 'Путает период: для синуса и косинуса 2πn, для тангенса πn', fix: 'Сверьтесь с формулой: в tg x = a период πn.' },
    trig_range:        { home: 'trigeq',  title: 'Решает sin x = a при |a| > 1', fix: 'Синус и косинус принимают значения только от −1 до 1.' },
    pyth_add:          { home: 'planmet', title: 'Складывает сами катеты вместо их квадратов: c = a + b', fix: 'c² = a² + b², затем извлеките корень.' },
    pyth_leg:          { home: 'planmet', title: 'Складывает квадраты, когда нужно найти катет', fix: 'Катет: a² = c² − b².' },
    tri_area_half:     { home: 'planmet', title: 'Забывает делить на 2 в площади треугольника', fix: 'S = a·h/2.' },
    sim_area:          { home: 'planmet', title: 'Считает, что площади подобных фигур относятся как k, а не как k²', fix: 'Отношение площадей равно k².' },
    odz_ignore:        { home: 'ratq',    title: 'Не исключает значения, при которых знаменатель равен нулю', fix: 'Сначала ОДЗ: корни, обнуляющие знаменатель, отбрасываются.' },
    ineq_as_eq:        { home: 'qineq',   title: 'Решает неравенство как уравнение и записывает в ответ только нули', fix: 'Ответ неравенства — промежуток, а не отдельные числа.' },
    interval_sign:     { home: 'qineq',   title: 'Выбирает не тот интервал: путает «между корнями» и «вне корней»', fix: 'Подставьте число из интервала и проверьте знак.' },
    nlsys_one_sol:     { home: 'nlsys',   title: 'Находит только одну пару решений из двух', fix: 'У квадратного уравнения два корня — для каждого найдите пару.' },
    irr_extraneous:    { home: 'irr',     title: 'Не проверяет корни после возведения в квадрат', fix: 'Подставьте каждый корень в исходное уравнение: может быть посторонний.' },
    root_negative:     { home: 'irr',     title: 'Считает, что квадратный корень может равняться отрицательному числу', fix: '√a ≥ 0: уравнение √(…) = −2 решений не имеет.' },
    log_as_div:        { home: 'log',     title: 'Считает логарифм делением: log₂ 8 = 4', fix: 'logₐ b — это показатель степени: в какую степень возвести a, чтобы получить b.' },
    log_sum:           { home: 'log',     title: 'Считает, что log(a + b) = log a + log b', fix: 'Сумма логарифмов — это логарифм произведения: log a + log b = log(ab).' },
    log_domain:        { home: 'log',     title: 'Не проверяет, что выражение под логарифмом положительно', fix: 'В logₐ x всегда x > 0.' },
    sys_union:         { home: 'sysineq', title: 'Берёт объединение решений вместо пересечения', fix: 'Система — это «и»: подходит только общая часть.' },
    sys_one_only:      { home: 'sysineq', title: 'Учитывает только одно неравенство системы', fix: 'Ответ должен подходить каждому неравенству системы.' },
    exp_ineq_flip:     { home: 'elsys',   title: 'Не меняет знак неравенства при основании меньше 1', fix: 'При 0 < a < 1 знак при переходе к показателям разворачивается.' },
    deriv_power:       { home: 'deriv',   title: 'Не уменьшает показатель: (xⁿ)′ = n·xⁿ', fix: '(xⁿ)′ = n·xⁿ⁻¹.' },
    deriv_const:       { home: 'deriv',   title: 'Оставляет константу в производной', fix: 'Производная числа равна нулю.' },
    solid_count:       { home: 'solid',   title: 'Путает число граней, рёбер и вершин', fix: 'Проверьте, что именно спрашивают: грани, рёбра или вершины.' },
    diag_2d:           { home: 'solid',   title: 'Считает диагональ параллелепипеда только по двум измерениям', fix: 'd² = a² + b² + c² — все три измерения.' },
    vec_order:         { home: 'vec',     title: 'Вычитает координаты в обратном порядке (из начала конец)', fix: 'Вектор = координаты конца − координаты начала.' },
    vec_len_sum:       { home: 'vec',     title: 'Считает длину вектора как сумму координат', fix: '|a| = √(x² + y²).' },
    dot_as_vec:        { home: 'vec',     title: 'Перемножает координаты, но не складывает результаты', fix: 'Скалярное произведение — число: x₁x₂ + y₁y₂.' },
    integ_as_deriv:    { home: 'integ',   title: 'Берёт производную вместо того, чтобы интегрировать', fix: 'Первообразная — обратное действие: показатель увеличивается на 1.' },
    integ_no_divide:   { home: 'integ',   title: 'Увеличивает показатель, но не делит на новый показатель', fix: '∫xⁿdx = xⁿ⁺¹/(n + 1).' },
    integ_bounds:      { home: 'integ',   title: 'Неверно подставляет пределы: F(a) − F(b) или только F(b)', fix: 'F(верхний предел) − F(нижний предел).' },
    vol_third:         { home: 'solmet',  title: 'Забывает коэффициент 1/3 в объёме пирамиды и конуса', fix: 'V = S_осн·h/3.' },
    vol_area_mix:      { home: 'solmet',  title: 'Путает объём с площадью поверхности', fix: 'Объём измеряется в кубических единицах, площадь — в квадратных.' },
    scale_cube:        { home: 'solmet',  title: 'Считает, что при увеличении ребра в k раз объём растёт тоже в k раз', fix: 'Объём растёт в k³ раз.' },
    mid_diff:          { home: 'vec3',    title: 'Для середины отрезка берёт полуразность вместо полусуммы', fix: 'Середина — полусумма координат концов.' }
  });

  T.QUESTIONS.push(
    // trig
    { id: 'trig1', topic: 'trig', text: 'Вычислите: sin 30°', options: [{ t: '1/2', ok: true }, { t: '√3/2', mis: 'trig_swap' }, { t: '√2/2' }, { t: '1' }] },
    { id: 'trig2', topic: 'trig', text: 'Вычислите: cos 30°', options: [{ t: '√3/2', ok: true }, { t: '1/2', mis: 'trig_swap' }, { t: '√2/2' }, { t: '0' }] },
    { id: 'trig3', topic: 'trig', text: 'Вычислите: tg 45°', options: [{ t: '1', ok: true }, { t: '√2/2' }, { t: '0' }, { t: '√3' }] },
    { id: 'trig4', topic: 'trig', text: 'sin α = 3/5, угол α в первой четверти. Найдите cos α.', options: [{ t: '4/5', ok: true }, { t: '2/5', mis: 'trig_identity' }, { t: '−4/5', mis: 'trig_sign_quarter' }, { t: '16/25' }] },
    { id: 'trig5', topic: 'trig', text: 'Упростите: 1 − sin²α', options: [{ t: 'cos²α', ok: true }, { t: 'cos α', mis: 'trig_identity' }, { t: 'sin²α' }, { t: '−cos²α' }] },
    { id: 'trig6', topic: 'trig', text: 'cos α = −1/2, угол α во второй четверти. Найдите sin α.', options: [{ t: '√3/2', ok: true }, { t: '−√3/2', mis: 'trig_sign_quarter' }, { t: '1/2' }, { t: '3/4' }] },
    // planfig
    { id: 'planfig1', topic: 'planfig', text: 'Два угла треугольника равны 50° и 60°. Найдите третий угол.', options: [{ t: '70°', ok: true }, { t: '250°', mis: 'angle_sum' }, { t: '110°', mis: 'answer_wrong_qty' }, { t: '80°' }] },
    { id: 'planfig2', topic: 'planfig', text: 'Один из смежных углов равен 70°. Найдите второй.', options: [{ t: '110°', ok: true }, { t: '70°', mis: 'adjacent_vertical' }, { t: '20°' }, { t: '290°' }] },
    { id: 'planfig3', topic: 'planfig', text: 'Угол при вершине равнобедренного треугольника равен 40°. Найдите угол при основании.', options: [{ t: '70°', ok: true }, { t: '140°' }, { t: '40°' }, { t: '160°', mis: 'angle_sum' }] },
    { id: 'planfig4', topic: 'planfig', text: 'Три угла четырёхугольника равны 80°, 90° и 100°. Найдите четвёртый.', options: [{ t: '90°', ok: true }, { t: '270°', mis: 'answer_wrong_qty' }, { t: '100°' }, { t: '80°' }] },
    { id: 'planfig5', topic: 'planfig', text: 'Центральный угол окружности равен 80°. Найдите вписанный угол, опирающийся на ту же дугу.', options: [{ t: '40°', ok: true }, { t: '80°', mis: 'inscribed_central' }, { t: '160°' }, { t: '100°' }] },
    { id: 'planfig6', topic: 'planfig', text: 'Один из вертикальных углов равен 35°. Найдите второй.', options: [{ t: '35°', ok: true }, { t: '145°', mis: 'adjacent_vertical' }, { t: '55°' }, { t: '325°' }] },
    // exp
    { id: 'exp1', topic: 'exp', text: 'Решите уравнение: 2^x = 8', options: [{ t: 'x = 3', ok: true }, { t: 'x = 4', mis: 'pow_as_mult' }, { t: 'x = 6' }, { t: 'x = 16' }] },
    { id: 'exp2', topic: 'exp', text: 'Решите уравнение: 3^x = 1', options: [{ t: 'x = 0', ok: true }, { t: 'x = 1' }, { t: 'x = 1/3', mis: 'pow_as_mult' }, { t: 'Корней нет' }] },
    { id: 'exp3', topic: 'exp', text: 'Решите уравнение: 2^x = 1/4', options: [{ t: 'x = −2', ok: true }, { t: 'x = 2' }, { t: 'x = 1/8', mis: 'pow_as_mult' }, { t: 'Корней нет', mis: 'exp_neg_power' }] },
    { id: 'exp4', topic: 'exp', text: 'Решите уравнение: 4^x = 8', options: [{ t: 'x = 3/2', ok: true }, { t: 'x = 2', mis: 'pow_as_mult' }, { t: 'x = 3', mis: 'exp_base' }, { t: 'x = 2/3' }] },
    { id: 'exp5', topic: 'exp', text: 'Решите уравнение: 5^(x − 1) = 25', options: [{ t: 'x = 3', ok: true }, { t: 'x = 1', mis: 'eq_move_sign' }, { t: 'x = 6', mis: 'pow_as_mult' }, { t: 'x = 2' }] },
    { id: 'exp6', topic: 'exp', text: 'Решите уравнение: 3^(2x) = 81', options: [{ t: 'x = 2', ok: true }, { t: 'x = 4' }, { t: 'x = 13,5', mis: 'pow_as_mult' }, { t: 'x = 8' }] },
    // prog
    { id: 'prog1', topic: 'prog', text: 'Арифметическая прогрессия: a₁ = 2, d = 3. Найдите a₅.', options: [{ t: '14', ok: true }, { t: '17', mis: 'prog_n' }, { t: '162', mis: 'prog_mix' }, { t: '11' }] },
    { id: 'prog2', topic: 'prog', text: 'Арифметическая прогрессия: 5, 8, 11, … Найдите сумму первых четырёх членов.', options: [{ t: '38', ok: true }, { t: '14', mis: 'answer_wrong_qty' }, { t: '24' }, { t: '52' }] },
    { id: 'prog3', topic: 'prog', text: 'Геометрическая прогрессия: b₁ = 3, q = 2. Найдите b₄.', options: [{ t: '24', ok: true }, { t: '48', mis: 'prog_n' }, { t: '9', mis: 'prog_mix' }, { t: '18' }] },
    { id: 'prog4', topic: 'prog', text: 'Найдите разность арифметической прогрессии, если a₁ = 7, a₃ = 15.', options: [{ t: '4', ok: true }, { t: '8' }, { t: '8/3', mis: 'prog_n' }, { t: '11' }] },
    { id: 'prog5', topic: 'prog', text: 'Геометрическая прогрессия: 2, 6, 18, … Найдите знаменатель q.', options: [{ t: '3', ok: true }, { t: '4', mis: 'prog_mix' }, { t: '12' }, { t: '1/3' }] },
    { id: 'prog6', topic: 'prog', text: 'Найдите сумму первых десяти членов арифметической прогрессии, если a₁ = 1, a₁₀ = 19.', options: [{ t: '100', ok: true }, { t: '200' }, { t: '19', mis: 'answer_wrong_qty' }, { t: '190' }] },
    // trigeq
    { id: 'trigeq1', topic: 'trigeq', text: 'Решите уравнение: sin x = 0', options: [{ t: 'x = πn, n ∈ Z', ok: true }, { t: 'x = 2πn, n ∈ Z', mis: 'trig_period' }, { t: 'x = 0', mis: 'trig_one_series' }, { t: 'x = π/2 + πn, n ∈ Z' }] },
    { id: 'trigeq2', topic: 'trigeq', text: 'Решите уравнение: cos x = 1', options: [{ t: 'x = 2πn, n ∈ Z', ok: true }, { t: 'x = πn, n ∈ Z', mis: 'trig_period' }, { t: 'x = 0', mis: 'trig_one_series' }, { t: 'x = π/2 + 2πn, n ∈ Z' }] },
    { id: 'trigeq3', topic: 'trigeq', text: 'Решите уравнение: cos x = 1/2', options: [{ t: 'x = ±π/3 + 2πn, n ∈ Z', ok: true }, { t: 'x = ±π/6 + 2πn, n ∈ Z', mis: 'trig_swap' }, { t: 'x = π/3', mis: 'trig_one_series' }, { t: 'x = ±π/3 + πn, n ∈ Z', mis: 'trig_period' }] },
    { id: 'trigeq4', topic: 'trigeq', text: 'Решите уравнение: sin x = 2', options: [{ t: 'Корней нет', ok: true }, { t: 'x = arcsin 2 + 2πn, n ∈ Z', mis: 'trig_range' }, { t: 'x = 2πn, n ∈ Z' }, { t: 'x = π/2 + 2πn, n ∈ Z' }] },
    { id: 'trigeq5', topic: 'trigeq', text: 'Решите уравнение: tg x = 1', options: [{ t: 'x = π/4 + πn, n ∈ Z', ok: true }, { t: 'x = π/4 + 2πn, n ∈ Z', mis: 'trig_period' }, { t: 'x = π/4', mis: 'trig_one_series' }, { t: 'x = π/2 + πn, n ∈ Z' }] },
    { id: 'trigeq6', topic: 'trigeq', text: 'Решите уравнение: 2 sin x − 1 = 0', options: [{ t: 'x = (−1)ⁿ·π/6 + πn, n ∈ Z', ok: true }, { t: 'x = (−1)ⁿ·π/3 + πn, n ∈ Z', mis: 'trig_swap' }, { t: 'x = π/6', mis: 'trig_one_series' }, { t: 'x = ±π/6 + 2πn, n ∈ Z' }] },
    // planmet
    { id: 'planmet1', topic: 'planmet', text: 'Катеты прямоугольного треугольника равны 6 см и 8 см. Найдите гипотенузу.', options: [{ t: '10 см', ok: true }, { t: '14 см', mis: 'pyth_add' }, { t: '100 см' }, { t: '48 см' }] },
    { id: 'planmet2', topic: 'planmet', text: 'Гипотенуза равна 13 см, один катет — 5 см. Найдите второй катет.', options: [{ t: '12 см', ok: true }, { t: '8 см', mis: 'pyth_add' }, { t: '√194 см', mis: 'pyth_leg' }, { t: '18 см' }] },
    { id: 'planmet3', topic: 'planmet', text: 'Найдите площадь треугольника со стороной 10 см и высотой 6 см, проведённой к этой стороне.', options: [{ t: '30 см²', ok: true }, { t: '60 см²', mis: 'tri_area_half' }, { t: '16 см²' }, { t: '32 см²' }] },
    { id: 'planmet4', topic: 'planmet', text: 'Стороны прямоугольника равны 4 см и 7 см. Найдите его площадь.', options: [{ t: '28 см²', ok: true }, { t: '22 см²', mis: 'answer_wrong_qty' }, { t: '11 см²' }, { t: '14 см²' }] },
    { id: 'planmet5', topic: 'planmet', text: 'Треугольники подобны с коэффициентом 2. Площадь меньшего равна 5 см². Найдите площадь большего.', options: [{ t: '20 см²', ok: true }, { t: '10 см²', mis: 'sim_area' }, { t: '40 см²' }, { t: '25 см²' }] },
    { id: 'planmet6', topic: 'planmet', text: 'Найдите площадь круга радиуса 3 см.', options: [{ t: '9π см²', ok: true }, { t: '6π см²', mis: 'answer_wrong_qty' }, { t: '3π см²' }, { t: '36π см²' }] },
    // ratq
    { id: 'ratq1', topic: 'ratq', text: 'Решите уравнение: (x² − 4)/(x − 2) = 0', options: [{ t: 'x = −2', ok: true }, { t: 'x = ±2', mis: 'odz_ignore' }, { t: 'x = 2' }, { t: 'x = 4' }] },
    { id: 'ratq2', topic: 'ratq', text: 'Решите уравнение: 6/x = 3', options: [{ t: 'x = 2', ok: true }, { t: 'x = 18', mis: 'prop_cross_wrong' }, { t: 'x = 1/2' }, { t: 'x = 3' }] },
    { id: 'ratq3', topic: 'ratq', text: 'Решите уравнение: (x + 3)/(x − 1) = 2', options: [{ t: 'x = 5', ok: true }, { t: 'x = 4', mis: 'distribute_partial' }, { t: 'x = −1', mis: 'eq_move_sign' }, { t: 'x = 1/3' }] },
    { id: 'ratq4', topic: 'ratq', text: 'Решите уравнение: x/(x − 3) = 3/(x − 3)', options: [{ t: 'Корней нет', ok: true }, { t: 'x = 3', mis: 'odz_ignore' }, { t: 'x = 0' }, { t: 'x = −3' }] },
    { id: 'ratq5', topic: 'ratq', text: 'Решите уравнение: 1/x + 1/2 = 1', options: [{ t: 'x = 2', ok: true }, { t: 'x = 2/3', mis: 'eq_move_sign' }, { t: 'x = 1/2' }, { t: 'x = 3' }] },
    { id: 'ratq6', topic: 'ratq', text: 'Решите уравнение: (x² − 9)/(x + 3) = 0', options: [{ t: 'x = 3', ok: true }, { t: 'x = ±3', mis: 'odz_ignore' }, { t: 'x = −3' }, { t: 'x = 9' }] },
    // qineq
    { id: 'qineq1', topic: 'qineq', text: 'Решите неравенство: x² − 5x + 6 < 0', options: [{ t: '2 < x < 3', ok: true }, { t: 'x < 2 или x > 3', mis: 'interval_sign' }, { t: 'x = 2 и x = 3', mis: 'ineq_as_eq' }, { t: 'x < 3' }] },
    { id: 'qineq2', topic: 'qineq', text: 'Решите неравенство: x² > 9', options: [{ t: 'x < −3 или x > 3', ok: true }, { t: 'x > 3', mis: 'quad_lose_root' }, { t: '−3 < x < 3', mis: 'interval_sign' }, { t: 'x > 9' }] },
    { id: 'qineq3', topic: 'qineq', text: 'Решите неравенство: x² − 4 ≤ 0', options: [{ t: '−2 ≤ x ≤ 2', ok: true }, { t: 'x ≤ 2', mis: 'quad_lose_root' }, { t: 'x ≤ −2 или x ≥ 2', mis: 'interval_sign' }, { t: 'x ≤ 4' }] },
    { id: 'qineq4', topic: 'qineq', text: 'Решите неравенство: (x − 1)(x + 2) > 0', options: [{ t: 'x < −2 или x > 1', ok: true }, { t: '−2 < x < 1', mis: 'interval_sign' }, { t: 'x > 1' }, { t: 'x < −1 или x > 2' }] },
    { id: 'qineq5', topic: 'qineq', text: 'Решите неравенство: (x − 3)/(x + 1) < 0', options: [{ t: '−1 < x < 3', ok: true }, { t: 'x < −1 или x > 3', mis: 'interval_sign' }, { t: 'x < 3' }, { t: '−3 < x < 1' }] },
    { id: 'qineq6', topic: 'qineq', text: 'Сколько целых решений у неравенства x² − 3x < 0?', options: [{ t: '2', ok: true }, { t: '4' }, { t: '3' }, { t: 'Бесконечно много', mis: 'interval_sign' }] },
    // nlsys
    { id: 'nlsys1', topic: 'nlsys', text: 'Решите систему: x + y = 5, xy = 6', options: [{ t: '(2; 3) и (3; 2)', ok: true }, { t: '(2; 3)', mis: 'nlsys_one_sol' }, { t: '(1; 6) и (6; 1)', mis: 'vieta_check' }, { t: '(−2; −3) и (−3; −2)', mis: 'vieta_sign' }] },
    { id: 'nlsys2', topic: 'nlsys', text: 'Решите систему: y = x², y = x + 2', options: [{ t: '(−1; 1) и (2; 4)', ok: true }, { t: '(2; 4)', mis: 'nlsys_one_sol' }, { t: '(1; 1) и (−2; 4)', mis: 'vieta_sign' }, { t: '(1; −1) и (4; 2)', mis: 'sys_order_swap' }] },
    { id: 'nlsys3', topic: 'nlsys', text: 'Решите систему: x − y = 1, x² + y² = 5', options: [{ t: '(2; 1) и (−1; −2)', ok: true }, { t: '(2; 1)', mis: 'nlsys_one_sol' }, { t: '(1; 2) и (−2; −1)', mis: 'sys_order_swap' }, { t: '(3; 2) и (−2; −3)' }] },
    { id: 'nlsys4', topic: 'nlsys', text: 'x + y = 4, x² − y² = 8. Найдите x.', options: [{ t: '3', ok: true }, { t: '1', mis: 'answer_wrong_qty' }, { t: '2' }, { t: '6' }] },
    { id: 'nlsys5', topic: 'nlsys', text: 'Решите систему: x = 3y, xy = 12', options: [{ t: '(6; 2) и (−6; −2)', ok: true }, { t: '(6; 2)', mis: 'nlsys_one_sol' }, { t: '(2; 6) и (−2; −6)', mis: 'sys_order_swap' }, { t: '(4; 3) и (−4; −3)' }] },
    { id: 'nlsys6', topic: 'nlsys', text: 'x² + y² = 25, y = 4. Найдите x.', options: [{ t: 'x = ±3', ok: true }, { t: 'x = 3', mis: 'quad_lose_root' }, { t: 'x = 9' }, { t: 'x = ±21' }] },
    // irr
    { id: 'irr1', topic: 'irr', text: 'Решите уравнение: √x = 3', options: [{ t: 'x = 9', ok: true }, { t: 'x = 6', mis: 'root_as_half' }, { t: 'x = √3' }, { t: 'x = 3' }] },
    { id: 'irr2', topic: 'irr', text: 'Решите уравнение: √(x + 1) = 2', options: [{ t: 'x = 3', ok: true }, { t: 'x = 1' }, { t: 'x = 5', mis: 'eq_move_sign' }, { t: 'x = 4' }] },
    { id: 'irr3', topic: 'irr', text: 'Решите уравнение: √(2x − 1) = −3', options: [{ t: 'Корней нет', ok: true }, { t: 'x = 5', mis: 'root_negative' }, { t: 'x = −1' }, { t: 'x = −4' }] },
    { id: 'irr4', topic: 'irr', text: 'Решите уравнение: √(x + 2) = x', options: [{ t: 'x = 2', ok: true }, { t: 'x = 2 и x = −1', mis: 'irr_extraneous' }, { t: 'x = −1' }, { t: 'x = 4' }] },
    { id: 'irr5', topic: 'irr', text: 'Решите уравнение: √(x² − 9) = 4', options: [{ t: 'x = ±5', ok: true }, { t: 'x = 5', mis: 'quad_lose_root' }, { t: 'x = 7', mis: 'root_of_sum' }, { t: 'x = ±√13' }] },
    { id: 'irr6', topic: 'irr', text: 'Решите уравнение: √(x + 6) = x', options: [{ t: 'x = 3', ok: true }, { t: 'x = 3 и x = −2', mis: 'irr_extraneous' }, { t: 'x = −2' }, { t: 'x = 6' }] },
    // log
    { id: 'log1', topic: 'log', text: 'Вычислите: log₂ 8', options: [{ t: '3', ok: true }, { t: '4', mis: 'log_as_div' }, { t: '16' }, { t: '6' }] },
    { id: 'log2', topic: 'log', text: 'Вычислите: log₃ 1', options: [{ t: '0', ok: true }, { t: '1' }, { t: '3' }, { t: '1/3', mis: 'log_as_div' }] },
    { id: 'log3', topic: 'log', text: 'Вычислите: log₂ 4 + log₂ 8', options: [{ t: '5', ok: true }, { t: 'log₂ 12', mis: 'log_sum' }, { t: '6' }, { t: '32' }] },
    { id: 'log4', topic: 'log', text: 'Решите уравнение: log₃ x = 2', options: [{ t: 'x = 9', ok: true }, { t: 'x = 6', mis: 'log_as_div' }, { t: 'x = 8' }, { t: 'x = 2/3' }] },
    { id: 'log5', topic: 'log', text: 'Решите уравнение: log₂(x − 1) = 3', options: [{ t: 'x = 9', ok: true }, { t: 'x = 7', mis: 'eq_move_sign' }, { t: 'x = 10' }, { t: 'x = 4' }] },
    { id: 'log6', topic: 'log', text: 'Вычислите: log₅ 25 − log₅ 5', options: [{ t: '1', ok: true }, { t: 'log₅ 20', mis: 'log_sum' }, { t: '5' }, { t: '2' }] },
    // sysineq
    { id: 'sysineq1', topic: 'sysineq', text: 'Решите систему неравенств: x > 1, x ≤ 4', options: [{ t: '1 < x ≤ 4', ok: true }, { t: 'x > 1', mis: 'sys_one_only' }, { t: 'x ≤ 4' }, { t: 'Решений нет' }] },
    { id: 'sysineq2', topic: 'sysineq', text: 'Решите систему неравенств: 2x − 4 > 0, x − 5 < 0', options: [{ t: '2 < x < 5', ok: true }, { t: 'x > 2', mis: 'sys_one_only' }, { t: '−2 < x < 5', mis: 'eq_move_sign' }, { t: 'x > 5' }] },
    { id: 'sysineq3', topic: 'sysineq', text: 'Решите систему неравенств: x ≥ 3, x < 1', options: [{ t: 'Решений нет', ok: true }, { t: '1 < x ≤ 3' }, { t: 'x ≥ 3', mis: 'sys_one_only' }, { t: 'x < 1 или x ≥ 3', mis: 'sys_union' }] },
    { id: 'sysineq4', topic: 'sysineq', text: 'Решите систему неравенств: 3x + 1 ≥ 7, −x > −6', options: [{ t: '2 ≤ x < 6', ok: true }, { t: 'x > 6', mis: 'ineq_flip' }, { t: '2 ≤ x ≤ 6' }, { t: 'x ≥ 2', mis: 'sys_one_only' }] },
    { id: 'sysineq5', topic: 'sysineq', text: 'Сколько целых чисел удовлетворяет системе: x > −2, x ≤ 3?', options: [{ t: '5', ok: true }, { t: '6' }, { t: '4' }, { t: 'Бесконечно много', mis: 'sys_one_only' }] },
    { id: 'sysineq6', topic: 'sysineq', text: 'Решите систему неравенств: x² < 9, x > 0', options: [{ t: '0 < x < 3', ok: true }, { t: '−3 < x < 3', mis: 'sys_one_only' }, { t: 'x > 3', mis: 'interval_sign' }, { t: 'x > 0' }] },
    // elsys
    { id: 'elsys1', topic: 'elsys', text: 'Решите неравенство: 2^x > 8', options: [{ t: 'x > 3', ok: true }, { t: 'x < 3' }, { t: 'x > 4', mis: 'pow_as_mult' }, { t: 'x > 2' }] },
    { id: 'elsys2', topic: 'elsys', text: 'Решите неравенство: (1/2)^x > 4', options: [{ t: 'x < −2', ok: true }, { t: 'x > −2', mis: 'exp_ineq_flip' }, { t: 'x > 2' }, { t: 'x < 2' }] },
    { id: 'elsys3', topic: 'elsys', text: 'Решите неравенство: log₂ x > 3', options: [{ t: 'x > 8', ok: true }, { t: 'x > 6', mis: 'log_as_div' }, { t: 'x > 9' }, { t: 'x < 8' }] },
    { id: 'elsys4', topic: 'elsys', text: 'Решите неравенство: log₃ x < 2', options: [{ t: '0 < x < 9', ok: true }, { t: 'x < 9', mis: 'log_domain' }, { t: 'x < 6', mis: 'log_as_div' }, { t: 'x > 9' }] },
    { id: 'elsys5', topic: 'elsys', text: 'Решите систему: 2^x = 8, x + y = 5', options: [{ t: '(3; 2)', ok: true }, { t: '(2; 3)', mis: 'sys_order_swap' }, { t: '(4; 1)', mis: 'pow_as_mult' }, { t: '(3; 5)' }] },
    { id: 'elsys6', topic: 'elsys', text: 'Решите систему: log₂ x = 3, x − y = 2', options: [{ t: '(8; 6)', ok: true }, { t: '(6; 4)', mis: 'log_as_div' }, { t: '(8; 10)', mis: 'eq_move_sign' }, { t: '(9; 7)' }] },
    // deriv
    { id: 'deriv1', topic: 'deriv', text: 'Найдите производную: f(x) = x³', options: [{ t: '3x²', ok: true }, { t: '3x³', mis: 'deriv_power' }, { t: 'x²' }, { t: 'x⁴/4' }] },
    { id: 'deriv2', topic: 'deriv', text: 'Найдите производную: f(x) = 5x² − 3x + 7', options: [{ t: '10x − 3', ok: true }, { t: '10x − 3 + 7', mis: 'deriv_const' }, { t: '5x − 3' }, { t: '10x² − 3x', mis: 'deriv_power' }] },
    { id: 'deriv3', topic: 'deriv', text: 'f(x) = x² + 4x. Найдите f′(1).', options: [{ t: '6', ok: true }, { t: '5', mis: 'answer_wrong_qty' }, { t: '2' }, { t: '8' }] },
    { id: 'deriv4', topic: 'deriv', text: 'Найдите угловой коэффициент касательной к графику y = x² в точке x₀ = 3.', options: [{ t: '6', ok: true }, { t: '9', mis: 'answer_wrong_qty' }, { t: '3' }, { t: '2' }] },
    { id: 'deriv5', topic: 'deriv', text: 'В какой точке производная функции f(x) = x² − 6x равна нулю?', options: [{ t: 'x = 3', ok: true }, { t: 'x = 6' }, { t: 'x = 0' }, { t: 'x = −3', mis: 'eq_move_sign' }] },
    { id: 'deriv6', topic: 'deriv', text: 'Найдите производную: f(x) = 2x⁴', options: [{ t: '8x³', ok: true }, { t: '8x⁴', mis: 'deriv_power' }, { t: '2x³' }, { t: '6x³' }] },
    // solid
    { id: 'solid1', topic: 'solid', text: 'Сколько рёбер у куба?', options: [{ t: '12', ok: true }, { t: '8', mis: 'solid_count' }, { t: '6' }, { t: '16' }] },
    { id: 'solid2', topic: 'solid', text: 'Сколько граней у треугольной призмы?', options: [{ t: '5', ok: true }, { t: '9', mis: 'solid_count' }, { t: '6' }, { t: '3' }] },
    { id: 'solid3', topic: 'solid', text: 'Найдите диагональ куба с ребром 2 см.', options: [{ t: '2√3 см', ok: true }, { t: '2√2 см', mis: 'diag_2d' }, { t: '6 см' }, { t: '12 см' }] },
    { id: 'solid4', topic: 'solid', text: 'Измерения прямоугольного параллелепипеда равны 1 см, 2 см и 2 см. Найдите его диагональ.', options: [{ t: '3 см', ok: true }, { t: '5 см', mis: 'pyth_add' }, { t: '9 см' }, { t: '√5 см', mis: 'diag_2d' }] },
    { id: 'solid5', topic: 'solid', text: 'Сколько вершин у четырёхугольной пирамиды?', options: [{ t: '5', ok: true }, { t: '8', mis: 'solid_count' }, { t: '4' }, { t: '6' }] },
    { id: 'solid6', topic: 'solid', text: 'Сколько рёбер у шестиугольной призмы?', options: [{ t: '18', ok: true }, { t: '12', mis: 'solid_count' }, { t: '8' }, { t: '6' }] },
    // vec
    { id: 'vec1', topic: 'vec', text: 'A(1; 2), B(4; 6). Найдите координаты вектора AB.', options: [{ t: '(3; 4)', ok: true }, { t: '(−3; −4)', mis: 'vec_order' }, { t: '(5; 8)' }, { t: '(4; 3)', mis: 'sys_order_swap' }] },
    { id: 'vec2', topic: 'vec', text: 'Найдите длину вектора a = (3; 4).', options: [{ t: '5', ok: true }, { t: '7', mis: 'vec_len_sum' }, { t: '25' }, { t: '12' }] },
    { id: 'vec3', topic: 'vec', text: 'a = (1; 2), b = (3; −1). Найдите a + b.', options: [{ t: '(4; 1)', ok: true }, { t: '(4; 3)' }, { t: '(−2; 3)' }, { t: '(3; −2)', mis: 'dot_as_vec' }] },
    { id: 'vec4', topic: 'vec', text: 'Найдите скалярное произведение векторов a = (2; 3) и b = (4; −1).', options: [{ t: '5', ok: true }, { t: '(8; −3)', mis: 'dot_as_vec' }, { t: '11' }, { t: '8' }] },
    { id: 'vec5', topic: 'vec', text: 'При каком значении m векторы a = (2; m) и b = (3; −6) перпендикулярны?', options: [{ t: '1', ok: true }, { t: '−1', mis: 'eq_move_sign' }, { t: '−4' }, { t: '6' }] },
    { id: 'vec6', topic: 'vec', text: 'Найдите координаты вектора 3a, если a = (2; −1).', options: [{ t: '(6; −3)', ok: true }, { t: '(6; −1)', mis: 'distribute_partial' }, { t: '(5; 2)' }, { t: '(6; 3)' }] },
    // integ
    { id: 'integ1', topic: 'integ', text: 'Найдите первообразную функции f(x) = 2x', options: [{ t: 'x² + C', ok: true }, { t: '2 + C', mis: 'integ_as_deriv' }, { t: '2x² + C', mis: 'integ_no_divide' }, { t: 'x²/2 + C' }] },
    { id: 'integ2', topic: 'integ', text: 'Найдите первообразную функции f(x) = 3x²', options: [{ t: 'x³ + C', ok: true }, { t: '6x + C', mis: 'integ_as_deriv' }, { t: '3x³ + C', mis: 'integ_no_divide' }, { t: 'x³/3 + C' }] },
    { id: 'integ3', topic: 'integ', text: 'Вычислите: ∫₀² 2x dx', options: [{ t: '4', ok: true }, { t: '2' }, { t: '8', mis: 'integ_no_divide' }, { t: '−4', mis: 'integ_bounds' }] },
    { id: 'integ4', topic: 'integ', text: 'Вычислите: ∫₁³ 1 dx', options: [{ t: '2', ok: true }, { t: '3', mis: 'integ_bounds' }, { t: '4' }, { t: '0', mis: 'integ_as_deriv' }] },
    { id: 'integ5', topic: 'integ', text: 'Вычислите: ∫₀¹ 3x² dx', options: [{ t: '1', ok: true }, { t: '3', mis: 'integ_no_divide' }, { t: '6', mis: 'integ_as_deriv' }, { t: '1/3' }] },
    { id: 'integ6', topic: 'integ', text: 'Найдите площадь фигуры, ограниченной линиями y = x, y = 0, x = 4.', options: [{ t: '8', ok: true }, { t: '16', mis: 'integ_no_divide' }, { t: '4' }, { t: '2' }] },
    // solmet
    { id: 'solmet1', topic: 'solmet', text: 'Найдите объём куба с ребром 3 см.', options: [{ t: '27 см³', ok: true }, { t: '9 см³', mis: 'pow_as_mult' }, { t: '54 см³', mis: 'vol_area_mix' }, { t: '18 см³' }] },
    { id: 'solmet2', topic: 'solmet', text: 'Найдите площадь поверхности куба с ребром 2 см.', options: [{ t: '24 см²', ok: true }, { t: '8 см²', mis: 'vol_area_mix' }, { t: '4 см²' }, { t: '16 см²' }] },
    { id: 'solmet3', topic: 'solmet', text: 'Основание пирамиды — квадрат со стороной 3 см, высота пирамиды 4 см. Найдите объём.', options: [{ t: '12 см³', ok: true }, { t: '36 см³', mis: 'vol_third' }, { t: '18 см³' }, { t: '48 см³' }] },
    { id: 'solmet4', topic: 'solmet', text: 'Найдите объём цилиндра с радиусом основания 2 см и высотой 5 см.', options: [{ t: '20π см³', ok: true }, { t: '10π см³' }, { t: '40π см³' }, { t: '100π см³' }] },
    { id: 'solmet5', topic: 'solmet', text: 'Ребро куба увеличили в 2 раза. Во сколько раз увеличился объём?', options: [{ t: '8', ok: true }, { t: '2', mis: 'scale_cube' }, { t: '4' }, { t: '6' }] },
    { id: 'solmet6', topic: 'solmet', text: 'Найдите объём конуса с радиусом основания 3 см и высотой 4 см.', options: [{ t: '12π см³', ok: true }, { t: '36π см³', mis: 'vol_third' }, { t: '4π см³' }, { t: '16π см³' }] },
    // vec3
    { id: 'vec31', topic: 'vec3', text: 'Найдите длину вектора a = (1; 2; 2).', options: [{ t: '3', ok: true }, { t: '5', mis: 'vec_len_sum' }, { t: '9' }, { t: '√5' }] },
    { id: 'vec32', topic: 'vec3', text: 'A(1; 0; 2), B(3; 4; 5). Найдите координаты вектора AB.', options: [{ t: '(2; 4; 3)', ok: true }, { t: '(−2; −4; −3)', mis: 'vec_order' }, { t: '(4; 4; 7)' }, { t: '(2; 4; 7)' }] },
    { id: 'vec33', topic: 'vec3', text: 'Найдите скалярное произведение векторов a = (1; 2; 3) и b = (2; 0; −1).', options: [{ t: '−1', ok: true }, { t: '(2; 0; −3)', mis: 'dot_as_vec' }, { t: '5' }, { t: '1' }] },
    { id: 'vec34', topic: 'vec3', text: 'Найдите середину отрезка AB, если A(2; 4; 6), B(4; 0; 2).', options: [{ t: '(3; 2; 4)', ok: true }, { t: '(1; −2; −2)', mis: 'mid_diff' }, { t: '(6; 4; 8)' }, { t: '(2; −4; −4)' }] },
    { id: 'vec35', topic: 'vec3', text: 'a = (1; −2; 3), b = (2; 1; −1). Найдите a + b.', options: [{ t: '(3; −1; 2)', ok: true }, { t: '(−1; −3; 4)' }, { t: '(2; −2; −3)', mis: 'dot_as_vec' }, { t: '(3; 3; 4)' }] },
    { id: 'vec36', topic: 'vec3', text: 'При каком значении m векторы a = (1; m; 2) и b = (2; 1; −3) перпендикулярны?', options: [{ t: '4', ok: true }, { t: '−4', mis: 'eq_move_sign' }, { t: '8' }, { t: '0' }] }
  );

  /* Цели диагностики для новых веток. «Вся математика» стартует со всех тем, на которые больше ничто не опирается. */
  const tops = T.TOPICS.filter(t => !T.TOPICS.some(o => o.prereq.includes(t.id))).sort((a, b) => b.level - a.level).map(t => t.id);
  T.GOALS.push(
    { id: 'all', title: 'Вся математика ЕНТ', desc: 'Все темы: от арифметики до интеграла и стереометрии. Долго — можно остановить в любой момент', start: tops },
    { id: 'alg2', title: 'Алгебра 10–11 класса', desc: 'Логарифмы, показательные и тригонометрические уравнения, прогрессии', start: ['elsys', 'trigeq', 'irr', 'prog'] },
    { id: 'calc', title: 'Начала анализа', desc: 'Производная и интеграл', start: ['integ'] },
    { id: 'geom', title: 'Геометрия', desc: 'Планиметрия, стереометрия, векторы', start: ['solmet', 'vec3'] }
  );
})();
